# Generated by Django 4.2.7 on 2023-12-21 18:38

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("tg_user_id", models.CharField(primary_key=True, serialize=False, unique=True)),
                ("short_name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("status", models.CharField(default="client", max_length=50)),
                ("tg_chat_id", models.CharField()),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
    ]
