# Generated by Django 4.2.7 on 2024-03-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "tg_user_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("short_name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("status", models.CharField(default="client", max_length=50)),
                ("tg_chat_id", models.CharField()),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "ordering": ["tg_user_id"],
            },
        ),
    ]
