# Generated by Django 4.2.7 on 2024-03-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='tg_chat_id',
        ),
        migrations.AlterField(
            model_name='person',
            name='tg_user_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
