# Generated by Django 4.2.7 on 2024-01-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
