# Generated by Django 5.1.1 on 2024-09-13 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="program",
            name="client_profile",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="client_profile",
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(fields=("user", "current_tg_id"), name="unique_tg_id_per_user"),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Program",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
