# Generated by Django 4.2.7 on 2024-04-30 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_person_profile_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='health_notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='workout_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='workout_goals',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
