# Generated by Django 5.1.1 on 2024-09-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_payment_profile_remove_program_client_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coachprofile",
            name="tax_identification",
        ),
    ]