# Generated by Django 4.2.7 on 2024-05-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_additional_info_profile_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='experience',
            new_name='work_experience',
        ),
    ]
