# Generated by Django 4.2.7 on 2024-05-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_experience_profile_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
