# Generated by Django 4.2.7 on 2024-05-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='training_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='assigned_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.CharField(default='basic', max_length=50),
            preserve_default=False,
        ),
    ]
