# Generated by Django 4.2.7 on 2024-05-14 08:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_subscription_subscription_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
