# Generated by Django 4.2.7 on 2024-05-14 08:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_assigned_to_profile_assigned_to_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
