# Generated by Django 4.2.7 on 2024-05-17 12:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assigned_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
