# Generated by Django 4.2.7 on 2024-06-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='type',
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
