# Generated by Django 4.2.7 on 2024-06-06 11:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_subscription_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='workout_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
