# Generated by Django 4.2.7 on 2024-06-06 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_subscription_workout_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='split_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
    ]
