# Generated by Django 4.2.7 on 2024-06-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_program_split_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='exercises',
        ),
        migrations.AddField(
            model_name='program',
            name='exercises_by_day',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
