# Generated by Django 4.2.7 on 2024-06-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_program_exercises_program_exercises_by_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='exercises',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
