# Generated by Django 4.2.7 on 2024-07-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_subscription_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_details',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
