# Generated by Django 5.2.2 on 2025-06-09 11:08

import apps.profiles.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(default="client", max_length=50)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("tg_id", models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
            },
        ),
        migrations.CreateModel(
            name="CoachProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("surname", models.CharField(blank=True, max_length=50, null=True)),
                ("additional_info", models.CharField(blank=True, max_length=250, null=True)),
                ("profile_photo", models.CharField(blank=True, max_length=250, null=True)),
                ("payment_details", apps.profiles.fields.EncryptedField(blank=True, max_length=250, null=True)),
                ("subscription_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("program_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "assigned_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="coach_profile", to="profiles.profile"
                    ),
                ),
            ],
            options={
                "verbose_name": "CoachProfile",
                "verbose_name_plural": "CoachProfiles",
            },
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("born_in", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("health_notes", models.CharField(blank=True, max_length=250, null=True)),
                ("workout_experience", models.CharField(blank=True, max_length=50, null=True)),
                ("workout_goals", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "assigned_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "ClientProfile",
                "verbose_name_plural": "ClientProfiles",
            },
        ),
    ]
