# Generated by Django 5.2.3 on 2025-06-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting_for_text", "Waiting For Text"),
                    ("default", "Default"),
                    ("waiting_for_subscription", "Waiting For Subscription"),
                    ("waiting_for_program", "Waiting For Program"),
                    ("initial", "Initial"),
                ],
                default="initial",
                max_length=50,
            ),
        ),
    ]
