# Generated by Django 5.2.2 on 2025-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="profile_photo",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
