# Generated by Django 5.2.3 on 2025-06-14 15:00

import apps.profiles.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_clientprofile_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachprofile",
            name="payment_details",
            field=apps.profiles.fields.EncryptedField(blank=True, null=True),
        ),
    ]
