# Generated by Django 5.2.3 on 2025-06-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_clientprofile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="credits",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
