# Generated by Django 5.2.3 on 2025-06-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_coachprofile_payment_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachprofile",
            name="work_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
