# Generated by Django 5.2.3 on 2025-06-30 00:00
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_coachprofile_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="credits",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
