# Generated by Django 5.2.3 on 2025-07-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_coachprofile_payout_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachprofile",
            name="coach_type",
            field=models.CharField(choices=[("human", "Human"), ("ai_coach", "Ai")], default="human", max_length=10),
        ),
    ]
