FROM python:3.12

ENV APP_HOME=/opt
ENV PYTHONPATH=$APP_HOME

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc python3-dev

WORKDIR $APP_HOME

ADD requirements.txt $APP_HOME/requirements.txt
ADD bot $APP_HOME/bot
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR $APP_HOME/bot

EXPOSE 8000