version: '3'

tasks:
  build:
    desc: Build Docker-container
    cmds:
      - docker-compose build

  up:
    desc: Start Docker-containers
    cmds:
      - docker-compose up

  down:
    desc: Stop Docker-containers
    cmds:
      - docker-compose down

  lint:
    desc: Run linters
    cmds:
      - ruff check --fix --config=pyproject.toml

  format:
    desc: Run formatter
    cmds:
      - ruff format --config=pyproject.toml

  tests:
    @pytest tests -v --ff