version: '3'

tasks:
  run:
    desc: Run production docker setup
    cmds:
      - docker compose -f docker-compose.yml up --build

  localrun:
    desc: Run bot locally
    env:
      COMPOSE_BAKE: 1
    cmds:
      - docker compose -f docker-compose-local.yml up --build

  lint:
    desc: Run linters (ruff + mypy)
    cmds:
      - uv run ruff check --fix --config=pyproject.toml
      - uv run mypy .

  format:
    desc: Format with Ruff
    cmds:
      - uv run ruff format --config=pyproject.toml

  test:
    desc: Run tests
    cmds:
      - uv run pytest

  update:
    desc: Update dependencies
    cmds:
      - uv lock --upgrade
      - uv sync

  update-win:
    desc: Sync deps in Windows venv
    cmds:
      - uv sync --active

  pre-commit:
    desc: Run pre-commit hooks
    cmds:
      - uv run pre-commit run --all-files

  migrate:
    desc: Make and apply Django migrations
    cmds:
      - uv run --env-file .env python manage.py makemigrations
      - uv run --env-file .env python manage.py migrate
