# Generated by Django 5.2.8 on 2025-11-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plans', '0004_exercises_default_list'),
        ('workout_plans', '0005_update_period_choices'),
    ]

    operations = [
    ]
