# Generated by Django 5.2.8 on 2025-11-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plans', '0006_merge_20251120_0859'),
        ('workout_plans', '0006_rename_client_profile_field'),
    ]

    operations = [
    ]
