from enum import Enum, auto


class ButtonText(Enum):
    female = auto()
    male = auto()
    client = auto()
    coach = auto()

    sign_in = auto()
    sign_up = auto()
    back = auto()
    quit = auto()
    forward = auto()
    save = auto()
    reset_program = auto()
    answer = auto()
    done = auto()
    get = auto()
    later = auto()
    select = auto()
    prev_menu = auto()
    delete = auto()
    pay = auto()

    my_clients = auto()
    my_profile = auto()
    my_program = auto()
    logout = auto()
    edit = auto()
    program = auto()
    subscription = auto()
    workout_goals = auto()
    workout_experience = auto()
    work_experience = auto()
    additional_info = auto()
    payment_details = auto()
    photo = auto()
    edit_exercise = auto()
    delete_exercise = auto()
    health_notes = auto()
    weight = auto()

    choose_coach = auto()
    contact_client = auto()
    contact_coach = auto()
    feedback = auto()

    beginner = auto()
    intermediate = auto()
    advanced = auto()
    experienced = auto()
    gym_workout = auto()
    home_workout = auto()
    street_workout = auto()

    add_exercise = auto()
    next_day = auto()
    sets = auto()
    reps = auto()
    exercises = auto()
    view = auto()
    create = auto()

    monday = auto()
    tuesday = auto()
    wednesday = auto()
    thursday = auto()
    friday = auto()
    saturday = auto()
    sunday = auto()
    edit_days = auto()

    answer_yes = auto()
    answer_no = auto()
    enabled = auto()
    disabled = auto()

    def __str__(self) -> str:
        return f"buttons.{self.name}"


class MessageText(Enum):
    username = auto()
    password = auto()
    email = auto()
    password_retype = auto()
    password_reset_sent = auto()
    registration_successful = auto()
    invalid_credentials = auto()
    password_mismatch = auto()
    password_requirements = auto()
    username_unavailable = auto()
    reset_password_offer = auto()
    password_unsafe = auto()
    invalid_content = auto()
    questionnaire_not_completed = auto()
    unexpected_error = auto()
    signed_in = auto()
    logout = auto()
    email_unavailable = auto()

    client_profile = auto()
    client_page = auto()
    client_default_status = auto()
    waiting_for_subscription = auto()
    waiting_for_program = auto()
    waiting_for_text = auto()
    choose_gender = auto()
    born_in = auto()
    workout_goals = auto()
    weight = auto()
    workout_experience = auto()
    health_notes = auto()
    workout_type = auto()

    coach_profile = auto()
    edit_profile = auto()
    choose_profile_parameter = auto()
    update_your_data = auto()
    name = auto()
    work_experience = auto()
    payment_details = auto()
    additional_info = auto()
    verified = auto()

    upload_photo = auto()
    photo_uploaded = auto()
    photo_upload_fail = auto()
    unable_to_delete_profile = auto()
    profile_deleted = auto()
    accept_policy = auto()
    your_data_updated = auto()
    choose_language = auto()
    choose_account_type = auto()

    choose_coach = auto()
    coach_selected = auto()
    coach_info_message = auto()
    new_coach_request = auto()
    coach_verified = auto()
    coach_declined = auto()
    contact_coach = auto()
    coach_page = auto()

    new_client = auto()
    contact_client = auto()
    enter_your_message = auto()

    enter_daily_program = auto()
    enter_exercise = auto()
    enter_sets = auto()
    enter_reps = auto()
    exercise_weight = auto()
    program_guide = auto()
    select_exercise = auto()
    continue_editing = auto()
    delete_confirmation = auto()
    parameter_to_edit = auto()
    workouts_number = auto()
    workouts_per_week = auto()
    select_days = auto()
    workout_plan_delete_warning = auto()
    workout_plan_deleted = auto()
    workout_days_changed = auto()
    program_not_ready = auto()
    complete_all_days = auto()
    no_program = auto()
    no_exercises_to_save = auto()
    no_clients = auto()
    no_coaches = auto()
    program_page = auto()
    program_view = auto()
    workout_results = auto()
    workout_feedback = auto()
    have_you_trained = auto()
    workout_completed = auto()
    keep_going = auto()
    workout_description = auto()

    payment_required = auto()
    payment_success = auto()
    payment_failure = auto()
    payment_in_progress = auto()
    subscription_page = auto()
    payment_link = auto()
    contract_info_message = auto()

    choose_action = auto()
    follow_link = auto()
    main_menu = auto()
    help = auto()
    start = auto()
    saved = auto()
    feedback = auto()
    feedback_sent = auto()
    message_sent = auto()
    incoming_message = auto()
    incoming_request = auto()

    out_of_range = auto()
    image_error = auto()
    no_profiles_found = auto()
    new_program = auto()
    wait_for_verification = auto()
    not_verified = auto()
    gift = auto()
    select_service = auto()

    def __str__(self) -> str:
        return f"messages.{self.name}"
