# Generated by Django 5.1.1 on 2024-09-12 14:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(default="client", max_length=50)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "assigned_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), blank=True, default=list, size=None
                    ),
                ),
                ("current_tg_id", models.BigIntegerField(blank=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_type", models.CharField(max_length=50)),
                ("handled", models.BooleanField(default=False)),
                ("shop_order_number", models.CharField(max_length=100, unique=True)),
                ("shop_bill_id", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(default="PENDING", max_length=50)),
                ("error", models.CharField(blank=True, max_length=250, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="accounts.profile"
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
            },
        ),
        migrations.CreateModel(
            name="CoachProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("surname", models.CharField(blank=True, max_length=50, null=True)),
                ("additional_info", models.CharField(blank=True, max_length=250, null=True)),
                ("profile_photo", models.CharField(blank=True, max_length=250, null=True)),
                ("payment_details", models.CharField(blank=True, max_length=250, null=True)),
                ("tax_identification", models.CharField(blank=True, max_length=250, null=True)),
                ("subscription_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("program_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="coach_profile", to="accounts.profile"
                    ),
                ),
            ],
            options={
                "verbose_name": "coach profile",
                "verbose_name_plural": "coach profiles",
            },
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("born_in", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("health_notes", models.CharField(blank=True, max_length=250, null=True)),
                ("workout_experience", models.CharField(blank=True, max_length=50, null=True)),
                ("workout_goals", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="accounts.coachprofile",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "client profile",
                "verbose_name_plural": "client profiles",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exercises_by_day", models.JSONField(blank=True, default=dict)),
                ("split_number", models.IntegerField(blank=True, null=True)),
                ("wishes", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="accounts.clientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "program",
                "verbose_name_plural": "programs",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "workout_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), blank=True, default=list, size=None
                    ),
                ),
                ("exercises", models.JSONField(blank=True, default=dict, null=True)),
                ("wishes", models.CharField(blank=True, max_length=500, null=True)),
                ("payment_date", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "client_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="accounts.clientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
    ]
