from enum import Enum, auto


class AutoName(str, Enum):
    def _generate_next_value_(name, start, count, last_values):
        return name


class ButtonText(AutoName):
    female = auto()
    male = auto()
    client = auto()
    coach = auto()

    back = auto()
    quit = auto()
    forward = auto()
    save = auto()
    reset_program = auto()
    answer = auto()
    done = auto()
    get = auto()
    later = auto()
    select = auto()
    prev_menu = auto()
    delete = auto()
    cancel_subscription = auto()
    pay = auto()
    new_program = auto()
    history = auto()
    tariff_plans = auto()
    start_plan = auto()
    optimum_plan = auto()
    max_plan = auto()
    subscription_6_months = auto()
    subscription_14_days = auto()
    subscription_30_days = auto()
    chat_message = auto()

    my_clients = auto()
    my_profile = auto()
    my_program = auto()
    balance = auto()
    edit = auto()
    program = auto()
    program_price = auto()
    subscription = auto()
    subscription_price = auto()
    workout_goals = auto()
    workout_experience = auto()
    work_experience = auto()
    additional_info = auto()
    payment_details = auto()
    photo = auto()
    edit_exercise = auto()
    delete_exercise = auto()
    toggle_drop_set = auto()
    health_notes = auto()
    weight = auto()

    choose_coach = auto()
    ai_coach = auto()
    contact_client = auto()
    contact_coach = auto()
    feedback = auto()

    beginner = auto()
    intermediate = auto()
    advanced = auto()
    experienced = auto()
    gym_workout = auto()
    home_workout = auto()

    add_exercise = auto()
    next_day = auto()
    sets = auto()
    set_mode = auto()
    reps = auto()
    exercises = auto()
    view = auto()
    create = auto()

    monday = auto()
    tuesday = auto()
    wednesday = auto()
    thursday = auto()
    friday = auto()
    saturday = auto()
    sunday = auto()
    edit_days = auto()

    answer_yes = auto()
    answer_no = auto()
    enabled = auto()
    disabled = auto()

    def __str__(self) -> str:
        return f"buttons.{self.name}"


class MessageText(AutoName):
    invalid_content = auto()
    questionnaire_not_completed = auto()
    unexpected_error = auto()

    client_profile = auto()
    client_page = auto()
    client_default_status = auto()
    waiting_for_subscription = auto()
    waiting_for_program = auto()
    waiting_for_text = auto()
    choose_gender = auto()
    born_in = auto()
    workout_goals = auto()
    weight = auto()
    workout_experience = auto()
    health_notes = auto()
    workout_type = auto()

    coach_profile = auto()
    edit_profile = auto()
    choose_profile_parameter = auto()
    update_your_data = auto()
    name = auto()  # pyre-ignore[bad-override]
    surname = auto()
    work_experience = auto()
    payment_details = auto()
    additional_info = auto()
    verified = auto()
    finish_registration_to_get_credits = auto()
    initial_credits_granted = auto()
    credit_balance = auto()
    not_enough_credits = auto()
    ai_coach_promo = auto()

    upload_photo = auto()
    photo_uploaded = auto()
    photo_upload_fail = auto()
    unable_to_delete_profile = auto()
    profile_deleted = auto()
    accept_policy = auto()
    your_data_updated = auto()
    select_language = auto()
    choose_account_type = auto()

    choose_coach = auto()
    ai_coach = auto()
    enter_wishes = auto()
    coach_selected = auto()
    coach_info_message = auto()
    new_coach_request = auto()
    coach_verified = auto()
    coach_declined = auto()
    contact_coach = auto()
    coach_page = auto()

    new_client = auto()
    contact_client = auto()
    enter_your_message = auto()

    enter_daily_program = auto()
    enter_exercise = auto()
    enter_sets = auto()
    enter_reps = auto()
    enter_program_price = auto()
    program_price = auto()
    enter_subscription_price = auto()
    subscription_price = auto()
    price_warning = auto()
    exercise_weight = auto()
    program_guide = auto()
    select_exercise = auto()
    continue_editing = auto()
    delete_confirmation = auto()
    parameter_to_edit = auto()
    workouts_number = auto()
    workouts_per_week = auto()
    select_days = auto()
    workout_plan_delete_warning = auto()
    workout_plan_deleted = auto()
    workout_days_changed = auto()
    program_not_ready = auto()
    complete_all_days = auto()
    no_program = auto()
    no_exercises_to_save = auto()
    no_clients = auto()
    no_coaches = auto()
    program_page = auto()
    program_view = auto()
    program_delete_warning = auto()
    workout_results = auto()
    workout_feedback = auto()
    have_you_trained = auto()
    workout_completed = auto()
    keep_going = auto()
    workout_description = auto()

    payment_required = auto()
    payment_success = auto()
    payment_failure = auto()
    payment_in_progress = auto()
    checkbox_reminding = auto()
    subscription_page = auto()
    subscription_canceled = auto()
    subscription_cancel_warning = auto()
    payment_link = auto()
    contract_info_message = auto()

    program_history_page = auto()
    subscription_history_page = auto()

    select_action = auto()
    follow_link = auto()
    main_menu = auto()
    help = auto()
    info = auto()
    start = auto()
    saved = auto()
    feedback = auto()
    feedback_sent = auto()
    new_feedback = auto()
    message_sent = auto()
    incoming_message = auto()
    incoming_request = auto()

    out_of_range = auto()
    image_error = auto()
    no_profiles_found = auto()
    new_program = auto()
    wait_for_verification = auto()
    not_verified = auto()
    gift = auto()
    select_service = auto()
    set_mode_on = auto()
    set_mode_off = auto()

    def __str__(self) -> str:
        return f"messages.{self.name}"
