from enum import Enum, auto


class AutoName(str, Enum):
    @staticmethod
    def _generate_next_value_(name: str, start: int, count: int, last_values: list[str]) -> str:
        return name


class ButtonText(AutoName):
    female = auto()
    male = auto()

    back = auto()
    quit = auto()
    forward = auto()
    save = auto()
    reset_program = auto()
    answer = auto()
    done = auto()
    later = auto()
    select = auto()
    prev_menu = auto()
    delete = auto()
    cancel_subscription = auto()
    pay = auto()
    new_workout_plan = auto()
    history = auto()
    tariff_plans = auto()
    start_plan = auto()
    optimum_plan = auto()
    max_plan = auto()
    subscription_6_months = auto()
    subscription_12_months = auto()
    subscription_1_month = auto()
    ask_ai = auto()
    ask_ai_again = auto()
    create_diet = auto()
    diet_again = auto()
    main_menu = auto()

    my_profile = auto()
    my_program = auto()
    services = auto()
    balance_status = auto()
    edit = auto()
    program = auto()
    subscription = auto()
    workout_goals = auto()
    workout_experience = auto()
    workout_location = auto()
    edit_exercise = auto()
    delete_exercise = auto()
    toggle_drop_set = auto()
    health_notes = auto()
    diet_allergies = auto()
    diet_products = auto()
    weight = auto()
    height = auto()

    feedback = auto()
    send_feedback = auto()
    faq = auto()

    beginner = auto()
    intermediate = auto()
    advanced = auto()
    experienced = auto()
    gym_workout = auto()
    home_workout = auto()

    add_exercise = auto()
    next_day = auto()
    sets = auto()
    set_mode = auto()
    reps = auto()
    exercises = auto()
    view = auto()
    create = auto()

    answer_yes = auto()
    answer_no = auto()
    enabled = auto()
    disabled = auto()
    plant_food = auto()
    meat = auto()
    fish_seafood = auto()
    eggs = auto()
    dairy = auto()

    def __str__(self) -> str:
        return f"buttons.{self.name}"


class MessageText(AutoName):
    invalid_content = auto()
    questionnaire_not_completed = auto()
    unexpected_error = auto()
    error_generic = auto()
    coach_agent_error = auto()

    profile_info = auto()
    client_page = auto()
    default_status = auto()
    waiting_for_subscription = auto()
    waiting_for_program = auto()
    request_in_progress = auto()
    waiting_for_text = auto()
    choose_gender = auto()
    born_in = auto()
    workout_goals = auto()
    workout_location = auto()
    weight = auto()
    height = auto()
    workout_experience = auto()
    health_notes = auto()
    health_notes_question = auto()
    diet_allergies_question = auto()
    diet_allergies = auto()
    diet_products = auto()

    edit_profile = auto()
    choose_profile_parameter = auto()
    update_your_data = auto()
    verified = auto()
    finish_registration_to_get_credits = auto()
    finish_registration = auto()
    initial_credits_granted = auto()
    credit_balance = auto()
    tariff_plans = auto()
    not_enough_credits = auto()
    ai_services = auto()
    confirm_service = auto()

    unable_to_delete_profile = auto()
    profile_deleted = auto()
    profile_data_not_found_error = auto()
    accept_policy = auto()
    your_data_updated = auto()
    select_language = auto()

    enter_wishes = auto()

    new_client = auto()
    enter_your_message = auto()

    enter_daily_program = auto()
    enter_exercise = auto()
    enter_sets = auto()
    enter_reps = auto()
    exercise_weight = auto()
    program_guide = auto()
    select_exercise = auto()
    continue_editing = auto()
    delete_confirmation = auto()
    parameter_to_edit = auto()
    workouts_number = auto()
    workouts_per_week = auto()
    workout_days_selection = auto()
    workout_plan_delete_warning = auto()
    workout_plan_deleted = auto()
    program_not_ready = auto()
    complete_all_days = auto()
    no_exercises_to_save = auto()
    no_exercises_found = auto()
    program_view = auto()
    program_delete_warning = auto()
    workout_results = auto()
    have_you_trained = auto()
    keep_going = auto()
    workout_description = auto()

    payment_required = auto()
    payment_success = auto()
    payment_failure = auto()
    payment_in_progress = auto()
    checkbox_reminding = auto()
    subscription_page = auto()
    subscription_canceled = auto()
    subscription_cancel_warning = auto()
    payment_link = auto()
    contract_info_message = auto()

    subscription_history_page = auto()

    select_action = auto()
    follow_link = auto()
    main_menu = auto()
    help = auto()
    info = auto()
    start = auto()
    saved = auto()
    feedback = auto()
    feedback_menu = auto()
    feedback_sent = auto()
    new_feedback = auto()
    message_sent = auto()
    ask_ai_response_template = auto()
    diet_response_template = auto()
    incoming_request = auto()

    ask_ai_prompt = auto()
    ask_ai_answer = auto()

    out_of_range = auto()
    image_error = auto()
    no_profiles_found = auto()
    new_workout_plan = auto()
    program_updated = auto()
    subscription_created = auto()
    subscription_not_found_error = auto()
    wait_for_verification = auto()
    not_verified = auto()
    gift = auto()
    set_mode_on = auto()
    set_mode_off = auto()

    def __str__(self) -> str:
        return f"messages.{self.name}"
