FROM python:3.12.0-slim

ENV APP_HOME=/opt
ENV STATIC_ROOT=/static
ENV DJANGO_SETTINGS_MODULE=backend.settings
ENV PYTHONPATH=$APP_HOME

WORKDIR $APP_HOME/
ADD requirements/requirements.backend.txt $APP_HOME/requirements.txt
ADD backend $APP_HOME/backend
RUN pip install -r requirements.txt

WORKDIR $APP_HOME/backend
# RUN python manage.py collectstatic --no-input

EXPOSE 8000