METRICS_EVENT_NEW_USER = "new_user"
METRICS_EVENT_ASK_AI_ANSWER = "ask_ai_answer"
METRICS_EVENT_DIET_PLAN = "diet_plan"
METRICS_EVENT_WORKOUT_PLAN = "workout_plan"

METRICS_EVENT_TYPES = (
    METRICS_EVENT_NEW_USER,
    METRICS_EVENT_ASK_AI_ANSWER,
    METRICS_EVENT_DIET_PLAN,
    METRICS_EVENT_WORKOUT_PLAN,
)

METRICS_SOURCE_PROFILE = "profile"
METRICS_SOURCE_ASK_AI = "ask_ai"
METRICS_SOURCE_DIET = "diet"
METRICS_SOURCE_WORKOUT_PLAN = "workout_plan"

METRICS_SOURCES = (
    METRICS_SOURCE_PROFILE,
    METRICS_SOURCE_ASK_AI,
    METRICS_SOURCE_DIET,
    METRICS_SOURCE_WORKOUT_PLAN,
)
