from .prompts import (
    COACH_SYSTEM_PROMPT,
    COACH_INSTRUCTIONS,
    GENERATE_WORKOUT,
    UPDATE_WORKOUT,
    ASK_AI_USER_PROMPT,
    CHAT_SUMMARY_PROMPT,
    REPLACE_EXERCISE_PROMPT,
    agent_instructions,
)

__all__ = [
    "COACH_SYSTEM_PROMPT",
    "COACH_INSTRUCTIONS",
    "GENERATE_WORKOUT",
    "UPDATE_WORKOUT",
    "ASK_AI_USER_PROMPT",
    "CHAT_SUMMARY_PROMPT",
    "REPLACE_EXERCISE_PROMPT",
    "agent_instructions",
]
