from .prompts import (
    COACH_SYSTEM_PROMPT,
    COACH_INSTRUCTIONS,
    GENERATE_WORKOUT,
    UPDATE_WORKOUT,
)

__all__ = [
    "COACH_SYSTEM_PROMPT",
    "COACH_INSTRUCTIONS",
    "GENERATE_WORKOUT",
    "UPDATE_WORKOUT",
]
