# Generated by Django 5.1.1 on 2024-09-17 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="shop_order_number",
            new_name="order_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="shop_bill_id",
        ),
    ]
