BOT_PAYMENT_OPTIONS = "https://storage.googleapis.com/payments_options/"
FIRST_NAME = "Євгеній"
LAST_NAME = "МЕЛЬНИКОВ"
ADDRESS = "вул. Пимоненка, 13"
PAYMENT_STATUS_PAYED = "PAYED"
PAYMENT_STATUS_REJECTED = "REJECTED"
