from aiogram.fsm.state import State, StatesGroup


class States(StatesGroup):
    action_choice = State()
    main_menu = State()
    feedback = State()

    language_choice = State()
    username = State()
    password = State()
    email = State()
    password_reset = State()
    password_retype = State()
    account_type = State()

    gender = State()
    born_in = State()
    name = State()
    workout_goals = State()
    workout_type = State()
    workouts_number = State()
    workout_days = State()
    weight = State()
    workout_experience = State()
    health_notes = State()
    work_experience = State()
    additional_info = State()
    payment_details = State()
    profile_photo = State()
    accept_policy = State()

    edit_profile = State()
    profile = State()
    profile_delete = State()

    workout_survey = State()
    workout_description = State()
    program_view = State()
    confirm_subscription_reset = State()
    exercise_weight = State()
    enter_sets = State()
    enter_reps = State()
    add_exercise_name = State()

    edit_exercise = State()
    edit_exercise_parameter = State()
    program_edit = State()
    delete_exercise = State()
    show_subscription = State()
    subscription_manage = State()
    program_manage = State()
    program_action_choice = State()

    new_coach_request = State()
    choose_coach = State()
    coach_selection = State()
    contact_coach = State()

    show_clients = State()
    contact_client = State()

    payment_choice = State()
    handle_payment = State()
    gift = State()
    select_service = State()
