from aiogram.fsm.state import State, StatesGroup


class States(StatesGroup):
    main_menu = State()
    language_choice = State()
    username = State()
    password = State()
    email = State()
    password_reset = State()
    password_retype = State()

    account_type = State()
    gender = State()
    birth_date = State()
    name = State()
    workout_goals = State()
    workout_type = State()
    weight = State()
    workout_experience = State()
    health_notes = State()
    work_experience = State()
    additional_info = State()
    payment_details = State()
    profile_photo = State()
    gift = State()

    edit_profile = State()
    action_choice = State()
    feedback = State()
    profile = State()
    program = State()
    new_coach_request = State
    choose_coach = State()
    coach_selection = State()
    show_clients = State()
    contact_client = State()
    program_manage = State()
    contact_coach = State()
    select_service = State()
    workouts_number = State()
    workout_days = State()
    subscription_manage = State()
    payment_choice = State()
    handle_payment = State()
    workout_survey = State()
    workout_description = State()
