from decimal import Decimal
from typing import Any, Protocol

from core.schemas import Profile


class ProfileRepository(Protocol):
    async def get_profile(self, profile_id: int) -> Profile | None: ...

    async def get_profile_by_tg_id(self, tg_id: int) -> Profile | None: ...

    async def create_profile(self, tg_id: int, language: str) -> Profile | None: ...

    async def update_profile(self, profile_id: int, data: dict[str, Any]) -> bool: ...

    async def delete_profile(self, profile_id: int) -> bool: ...

    async def adjust_credits(self, profile_id: int, delta: int | Decimal) -> bool: ...
