from decimal import Decimal
from typing import Any, Protocol

from core.schemas import Client, Profile


class ProfileRepository(Protocol):
    async def get_profile(self, profile_id: int) -> Profile | None: ...

    async def get_profile_by_tg_id(self, tg_id: int) -> Profile | None: ...

    async def create_profile(self, tg_id: int, language: str) -> Profile | None: ...

    async def update_profile(self, profile_id: int, data: dict[str, Any]) -> bool: ...

    async def delete_profile(self, profile_id: int, token: str | None = None) -> bool: ...

    async def create_client_profile(self, profile_id: int, data: dict[str, Any] | None = None) -> Client | None: ...

    async def update_client_profile(self, client_profile_id: int, data: dict[str, Any]) -> bool: ...

    async def adjust_client_credits(self, profile_id: int, delta: int | Decimal) -> bool: ...

    async def get_client(self, client_id: int) -> Client | None: ...

    async def get_client_by_profile_id(self, profile_id: int) -> Client | None: ...
    async def get_client_by_tg_id(self, tg_id: int) -> Client | None: ...
